# Generated by Django 2.2.14 on 2020-07-22 08:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gonderi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baslik', models.CharField(max_length=200)),
                ('icerik', models.TextField()),
                ('y_tarihi', models.DateTimeField(blank=True, null=True)),
                ('tag', models.CharField(blank=True, max_length=300, null=True)),
                ('yazar', models.ForeignKey(on_delete='on_delete', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
